definitions:
  models.ListeningItem:
    properties:
      audio_files:
        items:
          type: string
        type: array
      id:
        type: integer
      name:
        type: string
      part_list:
        items:
          $ref: '#/definitions/models.ListeningPartItem'
        type: array
      status:
        type: integer
      type:
        type: integer
    type: object
  models.ListeningListResponse:
    properties:
      items:
        items:
          $ref: '#/definitions/models.ListeningItem'
        type: array
      total:
        type: integer
    type: object
  models.ListeningPartItem:
    properties:
      id:
        type: integer
      name:
        type: string
      type:
        type: integer
      type_list:
        items:
          $ref: '#/definitions/models.ListeningTypeItem'
        type: array
    type: object
  models.ListeningPartListResponse:
    properties:
      items:
        items:
          $ref: '#/definitions/models.ListeningPartItem'
        type: array
      total:
        type: integer
    type: object
  models.ListeningQuestionItem:
    properties:
      answer: {}
      "no":
        type: string
      options:
        items:
          $ref: '#/definitions/models.OptionsItem'
        type: array
      question:
        type: string
    type: object
  models.ListeningTypeItem:
    properties:
      article_content:
        type: string
      matching_options:
        items:
          $ref: '#/definitions/models.MatchingOptionsItem'
        type: array
      picture:
        items:
          $ref: '#/definitions/models.PicturesItem'
        type: array
      question_list:
        items:
          $ref: '#/definitions/models.ListeningQuestionItem'
        type: array
      title:
        type: string
      type:
        type: integer
    type: object
  models.MatchingOptionsItem:
    properties:
      content:
        type: string
      label:
        type: string
    type: object
  models.OptionsItem:
    properties:
      label:
        type: string
      value:
        type: string
    type: object
  models.PicturesItem:
    properties:
      name:
        type: string
      url:
        type: string
    type: object
  models.ResponseData:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
    type: object
info:
  contact: {}
paths:
  /config/listening-part/list:
    post:
      consumes:
      - application/json
      description: 根据条件获取听力part列表，并返回分页结果
      parameters:
      - description: 试题名称
        in: query
        name: name
        type: string
      - description: 试题状态
        in: query
        name: status
        type: integer
      - description: 试题类型
        in: query
        name: type
        type: integer
      - description: 页码
        in: query
        name: pageNo
        required: true
        type: integer
      - description: 每页条数
        in: query
        name: pageLimit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/models.ResponseData'
            - properties:
                data:
                  $ref: '#/definitions/models.ListeningPartListResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/models.ResponseData'
            - properties:
                data:
                  type: object
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/models.ResponseData'
            - properties:
                data:
                  type: object
              type: object
      summary: 获取听力篇列表
      tags:
      - Listening
  /config/listening/list:
    post:
      consumes:
      - application/json
      description: 根据条件获取听力列表，并返回分页结果
      parameters:
      - description: 听力名称
        in: query
        name: name
        type: string
      - description: 听力状态
        in: query
        name: status
        type: integer
      - description: 试题类型
        in: query
        name: type
        type: integer
      - description: 页码
        in: query
        name: pageNo
        required: true
        type: integer
      - description: 每页条数
        in: query
        name: pageLimit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/models.ResponseData'
            - properties:
                data:
                  $ref: '#/definitions/models.ListeningListResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/models.ResponseData'
            - properties:
                data:
                  type: object
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/models.ResponseData'
            - properties:
                data:
                  type: object
              type: object
      summary: 获取听力套题列表
      tags:
      - Listening
  /login:
    post:
      consumes:
      - application/json
      description: 用户使用邮箱和验证码登录系统，如果用户不存在，则自动创建新用户
      parameters:
      - description: 用户邮箱地址
        in: body
        name: email
        required: true
        schema:
          type: string
      - description: 验证码
        in: body
        name: code
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ResponseData'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ResponseData'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/models.ResponseData'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ResponseData'
      summary: 用户登录
  /send-code:
    post:
      consumes:
      - application/json
      description: 生成6位随机验证码并发送到指定邮箱地址
      parameters:
      - description: 目标邮箱地址
        in: body
        name: email
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ResponseData'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ResponseData'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ResponseData'
      summary: 发送验证码到邮箱
  /user-info:
    post:
      consumes:
      - application/json
      description: 根据用户的Token获取用户信息
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ResponseData'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ResponseData'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/models.ResponseData'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ResponseData'
      summary: 获取用户信息
swagger: "2.0"
